apiVersion: v1
kind: Service
metadata:
  name: sia-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sia.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app.kubernetes.io/name: sia
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
